#!/usr/bin/env bash

#You will work on a codebase using Flasgger, you will need to install it locally first before starting the RestAPI

sudo apt-get remove -y python3-lxml

sudo pip3 remove flask_cors # if it was not installed yet

sudo pip3 remove flasgger

#If the RestAPI is not starting, please read the error message. Based on the(ses) error message(s), you will have to troubleshoot potential dependencies issues.
#jsonschema exception

#sudo pip3 uninstall -y jsonschema 

#sudo pip3 install jsonschema==3.0.1

#No module named 'pathlib2'

#sudo pip3 install pathlib2
