#!/usr/bin/env bash

echo "starting installing MySQLdb"

sudo apt-get install python3-dev -y

sudo apt-get install libmysqlclient-dev -y

sudo apt-get install zlib1g-dev -y

sudo pip install mysqlclient==2.0.3
